version: '3.8' # docker version
services:
  web:
    image: php:apache
    ports:
      - '80:80'
    volumes:
      - ./:/var/www/html/
  db: 
    image: mysql:latest
    environment:
      MYSQL_DATABASE: arena
      MYSQL_USER: arena
      MYSQL_PASSWORD: password #contrasenya que treballarem
      MYSQL_ALLOW_EMPTY_PASSWORD: 1 #config que podem fe buit pass
    volumes:
      - "./db:/docker-entrypoint-initdb.d"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8001:80"
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306